### ISSUE TITLE
Is the layoutnet trained for your ads banner dataset??

### ISSUE THREAD

**Issue by jaepoong** [salesforce/LayoutDETR#8]
Thank you for great work!!
I have question about your FID calculation.
For evaluating your layout quality. Are you specifically trained your layoutnet  about ads banner dataset??

**Comment by ningyu1991** [comment]
The layoutnet was trained and provided by: https://github.com/ktrk115/const_layout/blob/5287480505939345543fff0b9f2e5d541e6f84e2/download_model.sh#L16

**Comment by jaepoong** [comment]
Thank you for replying

I understand that the layoutNet was trained specifically on  ads banner dataset. is that right??

Thank you so much
